#!/usr/bin/env python
import os
import sys

env = SConscript("../godot-cpp.4.2/SConstruct")

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
cpp_path = ["src/"]

env.Append(CPPPATH=cpp_path)

sources = []
for i in cpp_path:
    sources += Glob(i + "*.cpp")

# Paths
lib_name = "nine_patch_sprite_2d"
lib_path = "bin/" + lib_name

env_suffix = env["suffix"]
suffix = env_suffix.replace("template_", "")

def get_macos_path():
    folder = lib_path + suffix + ".framework/"
    file = lib_name + suffix
    return folder + file

def get_win_path():
    return lib_path + suffix + env["SHLIBSUFFIX"]

if env["platform"] == "macos":
    library = env.SharedLibrary(get_macos_path(), source=sources, )
else:
    library = env.SharedLibrary(get_win_path(), source=sources, )

Default(library)